#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u main.py "$@"
python -u representativeplots_SFv4.py "$@"
python -u representativeplots_3v4.py "$@"
python -u summaryplots.py "$@"